apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: yahyamohamed1231@outlook.com
    privateKeySecretRef:
      name: issuer
    solvers:
      - dns01:
          route53:
            hostedZoneID: Z09493521KNPJHRYW4MMO
            region: eu-west-2
        selector:
          dnsZones:
            - tm-yahya.com
      - http01:
          ingress:
            class: nginx
