apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx-namespace
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: daraymonsta/nginx-257:dreamteam
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              cpu: "500m"
# Use the command kubectl apply -f deployment.yml to create the deployment
