service:
  enabled: true
  service:
    type: ClusterIP
ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    nginx.org/hsts: "false"
    cert-manager.io/cluster-issuer: issuer
  hosts:
    - grafana.tm-yahya.com
  tls:
    - hosts:
        - grafana.tm-yahya.com
      secretName: grafana-ingress-tls
